# Artificial Neural Network

### Importing the libraries

In [1]:
!pip3 install numpy pandas tensorflow

  Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

2024-03-09 16:51:32.228652: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
tf.__version__

'2.14.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset.iloc[:, 3:-1].columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [6]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(len(X[0]))

12


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [14]:
len(X_train[0])

12

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 2s 2ms/step - loss: 0.6005 - accuracy: 0.7220
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4751 - accuracy: 0.8004
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4439 - accuracy: 0.8070
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4281 - accuracy: 0.8135
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4173 - accuracy: 0.8186
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4082 - accuracy: 0.8251
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3996 - accuracy: 0.8319
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3911 - accuracy: 0.8379
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3826 - accuracy: 0.8426
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3746 - accuracy: 0.8470
E

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [21]:
def ann_predict(location,credit_score,gender,age,tenure,balance,number_of_products,has_credit_card,is_a_active_member,Estimated_salary):
    term1 = 0 
    term2 = 0
    term3 = 0
    if(location == "France"):
        term1 = 1
        term2 = 0
        term3 = 0
    elif (location == "Spain"):
        term1 = 0
        term2 = 0
        term3 = 1
    else:
        term1 = 0
        term2 = 1
        term3 = 0
    print(sc.transform([[term1, term2, term3,credit_score, gender, age, tenure,balance, number_of_products, has_credit_card, is_a_active_member,Estimated_salary]]))
    result = ann.predict(sc.transform([[term1, term2, term3,credit_score, gender, age, tenure,balance, number_of_products, has_credit_card, is_a_active_member,Estimated_salary]])) > 0.5
    return result

In [26]:
ann_predict("Spain",510,0,43,2,125510.82,1,1,1,79084.1)


[[-1.01460667 -0.5698444   1.74309049 -1.44891895 -1.09168714  0.39672976
  -1.031415    0.78997008 -0.92159124  0.64259497  0.9687384  -0.36652898]]
1/1 [==============================] - 0s 23ms/step


array([[False]])

In [23]:
import pickle
with open('model_building.pickle','wb') as f:
    pickle.dump(ann,f)


In [24]:
import json
columns = {
    'data_columns' : [col.lower() for col in dataset.iloc[:, 3:-1].columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.